# Generated by Django 3.2 on 2023-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cin',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
