# Generated by Django 3.2 on 2023-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0003_leaverequest_nbjour'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
