# Generated by Django 3.2 on 2023-07-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0004_leaverequest_leave_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='is_Absent',
        ),
    ]
