# Generated by Django 3.2 on 2023-07-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appk', '0005_rename_is_present_attendance_is_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
